client_id = "41d14c005fa4d321f1231c005bd1e34f"
name = "ccs-credit-approval"
application_url = "https://ccs-credit-approval-prod.onrender.com"
embedded = true

[access_scopes]
scopes = "read_customers,write_metaobject_definitions,write_metaobjects,write_products,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://ccs-credit-approval-prod.onrender.com/auth/callback",
  "https://ccs-credit-approval-prod.onrender.com/auth/shopify/callback",
  "https://ccs-credit-approval-prod.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = false
